version: "3"

services:
  webapp:
    image: webapp:v0.1
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: uvicorn webapp.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - .:/usr/src/app
  db:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
  celery:
    image: webapp:v0.1
    depends_on:
      - rabbit
      - webapp
      - db
    command: celery -A webapp.worker worker --loglevel=info
    volumes:
      - .:/usr/src/app
  rabbit:
    hostname: rabbit 
    image: "rabbitmq:3-management"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672"

  
